[tool.poetry]
name = "pythonproject11"
version = "0.1.0"
description = ""
authors = ["miplo <miplotnova@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
lesson = "^0.0.1"
serializers = "^0.2.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
